### ISSUE TITLE
System.AccessViolationException in mainForm.cs

### ISSUE THREAD

**Issue by xaclincoln** [lepipele/csharpWebCam#1]
hi, i tried to run the Demo app on my laptop. i'm using win8.1 32bit os.  A few seconds after the app draw the frame from the cameral, a AccessViolationException occured in mainFrom.cs at line 85. 
I tried to run the app several times , not every time the exception would be thrown. 
Could anyone to solve this problem?

**Comment by lepipele** [comment]
Seems it's hardware related:

http://stackoverflow.com/questions/5510115/randomly-occuring-accessviolationexception-in-gdi
http://stackoverflow.com/questions/18631210/net-access-violation-exception-with-system-drawing-dll-numericupdown

I don't have Win8.1 so I can't try it out - everything works fine on my machine
