### ISSUE TITLE
Update to VS2019, c++ 19 and manage n camera in parallel

### ISSUE THREAD

**Issue by mickagau** [lepipele/csharpWebCam#10]
Hello Thank you for this code.

I did modify source code to manage several webcams in parallel. Normally up to 10 but i did tests with 2 only.

Please let me know if i should send to you source code to update it.

Regards
Mickael

**Comment by achopijocoder** [comment]
I would like to see your solution, Would you share?

**Comment by Stephanowicz** [comment]
How about doin it the usual way with a PR or @least You could fork it....?

**Comment by mickagau** [comment]
Hello 
Sorry, i am not used with fork and PR ...
Don't want to break anything :)

Pls find attached source code.
VS2019, cpp v142, x64, framework 4.5
[Eqpt.WebCam.Driver.zip](https://github.com/rockstardev/csharpWebCam/files/8316057/Eqpt.WebCam.Driver.zip)


One good improvement would be to do a user control per camera to manage demo application but as i use only wrapper and lib in my finale app, i did a quick and dirty copy paste of all controls.
